import json
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
r=Path(__file__).resolve().parents[1]; d=json.loads((r/'works-data.json').read_text(encoding='utf-8')); w=next(x for x in d if x.get('clientId')=='dr_clovis_cmfs'); b=w.get('budget') or {}; items=b.get('items',[]); actual={}
for x in b.get('actuals',[]):
    if x.get('source')=='Pedido' or x.get('orderRef'): actual[x.get('itemId')]=actual.get(x.get('itemId'),0)+float(x.get('value') or 0)
items=[x for x in items if x.get('id') in actual]
money=lambda n:f'R$ {n:,.2f}'.replace(',','X').replace('.',',').replace('X','.'); planned=sum(float(x.get('plannedTotal') or 0) for x in items); spent=sum(actual.get(x.get('id'),0) for x in items); out=r/'output'/'pdf'/'exemplo-relatorio-gestao-obra-dr-clovis.pdf'; out.parent.mkdir(parents=True,exist_ok=True)
s=getSampleStyleSheet(); navy=colors.HexColor('#13233d'); lime=colors.HexColor('#b9d653'); soft=colors.HexColor('#f1f4f5'); styles=s; styles['Title'].fontName='Helvetica-Bold'; styles['Title'].fontSize=24; styles['Title'].textColor=colors.white; styles['Heading2'].textColor=navy
story=[Table([[Paragraph('ABSOLUTTA',styles['Title']),Paragraph('RELATÓRIO MENSAL',styles['Heading3'])],[Paragraph(w['details'].get('name','Dr. Clovis CMSF'),styles['Title']),Paragraph('Período inteiro registrado',styles['Normal'])]],colWidths=[125*mm,55*mm],style=TableStyle([('BACKGROUND',(0,0),(-1,-1),navy),('TEXTCOLOR',(0,0),(-1,-1),colors.white),('LEFTPADDING',(0,0),(-1,-1),8*mm),('TOPPADDING',(0,0),(-1,-1),7*mm),('BOTTOMPADDING',(0,0),(-1,-1),7*mm)])),Spacer(1,10*mm),Paragraph('GESTÃO DE OBRA',styles['Kicker'] if 'Kicker' in styles else styles['Normal']),Paragraph('Orçado × realizado',styles['Heading2']),Paragraph('Acompanhamento financeiro e operacional da obra com base nos registros atuais do painel.',styles['Normal']),Spacer(1,5*mm),Table([[Paragraph('ORÇADO',styles['Normal']),Paragraph('REALIZADO',styles['Normal']),Paragraph('SALDO',styles['Normal'])],[Paragraph(money(planned),styles['Title']),Paragraph(money(spent),styles['Title']),Paragraph(money(planned-spent),styles['Title'])]],colWidths=[60*mm]*3,style=TableStyle([('BACKGROUND',(0,0),(-1,-1),soft),('GRID',(0,0),(-1,-1),.5,colors.white),('LEFTPADDING',(0,0),(-1,-1),4*mm),('TOPPADDING',(0,0),(-1,-1),4*mm),('BOTTOMPADDING',(0,0),(-1,-1),4*mm)])),Paragraph('Resumo por categoria',styles['Heading2'])]
cats={}
for x in items: cats.setdefault(x.get('category','Sem categoria'),[0,0]); cats[x.get('category','Sem categoria')][0]+=float(x.get('plannedTotal') or 0); cats[x.get('category','Sem categoria')][1]+=actual.get(x.get('id'),0)
story.append(Table([[Paragraph('Categoria',styles['Normal']),Paragraph('Planejado',styles['Normal']),Paragraph('Realizado',styles['Normal']),Paragraph('Saldo',styles['Normal'])]]+[[Paragraph(k,styles['Normal']),Paragraph(money(v[0]),styles['Normal']),Paragraph(money(v[1]),styles['Normal']),Paragraph(money(v[0]-v[1]),styles['Normal'])] for k,v in cats.items()],colWidths=[90*mm,30*mm,30*mm,30*mm],style=TableStyle([('BACKGROUND',(0,0),(-1,0),soft),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#dfe5e8')),('ALIGN',(1,0),(-1,-1),'RIGHT'),('LEFTPADDING',(0,0),(-1,-1),3*mm),('TOPPADDING',(0,0),(-1,-1),3*mm),('BOTTOMPADDING',(0,0),(-1,-1),3*mm)])))
story += [Paragraph('Status da obra: '+w['details'].get('status','Planejamento'),styles['Heading2']),Paragraph('Detalhamento dos itens orçados',styles['Heading2'])]
rows=[[Paragraph(x,styles['Normal']) for x in ['Item','Descrição','Categoria','Orçado','Realizado','Saldo']]]+[[Paragraph(str(x.get('code','')),styles['Normal']),Paragraph(str(x.get('description','')),styles['Normal']),Paragraph(str(x.get('category','')),styles['Normal']),Paragraph(money(float(x.get('plannedTotal') or 0)),styles['Normal']),Paragraph(money(actual.get(x.get('id'),0)),styles['Normal']),Paragraph(money(float(x.get('plannedTotal') or 0)-actual.get(x.get('id'),0)),styles['Normal'])] for x in items]
story.append(Table(rows,colWidths=[15*mm,55*mm,38*mm,25*mm,25*mm,25*mm],repeatRows=1,style=TableStyle([('BACKGROUND',(0,0),(-1,0),soft),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#dfe5e8')),('VALIGN',(0,0),(-1,-1),'TOP'),('ALIGN',(3,0),(-1,-1),'RIGHT'),('FONTSIZE',(0,0),(-1,-1),7),('LEFTPADDING',(0,0),(-1,-1),2*mm),('TOPPADDING',(0,0),(-1,-1),2*mm),('BOTTOMPADDING',(0,0),(-1,-1),2*mm)])))
SimpleDocTemplate(str(out),pagesize=A4,leftMargin=15*mm,rightMargin=15*mm,topMargin=15*mm,bottomMargin=15*mm).build(story); print(out)
